# Generated by Django 6.0.4 on 2026-04-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('course', models.CharField(max_length=120)),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
